### ISSUE TITLE
hdmi

### ISSUE THREAD

**Issue by m1faridi** [shiecldk/ASUS-ZenBook-Pro-Duo-15-OLED-UX582-Hackintosh#1]
Hi
Your system and my system both use CPU (i9-10980HK) but the system model is different. I have msi and you asus
I want to know how you enabled hdmi. I can activate whatever I do

https://github.com/tunglamvghy/MSI-GE75-Raider-10SGS-hackintosh

**Comment by shiecldk** [comment]
Hi @m1faridi, I haven't really got the HDMI port works on my laptop. However, you can use USB-C to HDMI adaptor if your laptop has thunderbolt port. 4K@60Hz works on my laptop. I'm not sure if you could use USB-C (without thunderbolt) to get the HDMI adaptor work but you can always return the adaptor if you purchase it from Amazon within 30 days. I would try it that way.

As for the HDMI port, in theory, it would work without QE/CI (GPU acceleration) on unsupported Nvidia GPU. At least for desktop and macOS Catalina, I was able to get desktop 2080Ti HDMI port output with Intel 10 Gen CPU. I am not sure how that would work on laptop and on macOS Big Sur/Monterey. If I remember it correctly, it has something to do with choosing a headless framebuffer for UHD630 but that means you won't be able to use your main screen because UHD630 would have no output port. I could be wrong; maybe search some posts on tonymacx86 or InsanelyMac about how people get 2080Ti HDMI port works (without GPU acceleration of course) and adopt their implementation to your laptop.

Also, try to ask [acidanthera](https://github.com/acidanthera/UEFIGraphicsFB) how UEFIGraphicsFB.kext really works and if it can solve your problem there.

**Comment by shiecldk** [comment]
Check this thread also and let me know if you can get it work this way.
https://github.com/SchmockLord/Hackintosh-Intel-i9-10900k-Gigabyte-Z490-Vision-D/issues/17

**Comment by m1faridi** [comment]
[](https://m.media-amazon.com/images/I/41947IoRFvL._AC_SY450_.jpg
)With usb-c to hdmi
Works ?

**Comment by shiecldk** [comment]
Not sure. Like I said, you would have to test it yourself. Since this is not related to this project, I have to close this thread. Please open issues in the GitHub repos you and I mentioned above instead.
