### ISSUE TITLE
Please remove my name from the readme.md

### ISSUE THREAD

**Issue by wern-apfel** [shiecldk/ASUS-ZenBook-Pro-Duo-15-OLED-UX582-Hackintosh#14]
Thanks. No more comments from me.

**Comment by wern-apfel** [comment]
Actually, I did not want to say anything more on this subject. 
For lack of time, I usually just skim the posts. Maybe I just misunderstood something.  If that is really the case, I must apologize. 

What do you mean by: (as he complained here) for some SSDTs for Qonfused's work ??
I have fixed the ScreenPad toggle and brightness adjustment, as well as the battery threshold and FN key lock. Even though the fix looks different, that doesn't mean it's from him.

**Comment by Qonfused** [comment]
The screenpad fix in my repo is not from you; please take a look here: [src/ACPI/SSDT-SPLC.dsl](https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/blob/main/src/ACPI/SSDT-SPLC.dsl)

This re-implements the DEVS methods based off work from @Plippo in the [asus-wmi-screenpad](https://github.com/Plippo/asus-wmi-screenpad) repository. I made a note of this [here](https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/issues/4#issuecomment-1328165864) when you first mentioned it for your EFI. I have a breakdown of references + notes [here](https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/blob/main/docs/resources/screenpad-plus.md#acpi---wmi-methods) that explains how it works. I've given another explanation of how these WMI methods work in his repo for other screenpad devices [here](https://github.com/Plippo/asus-wmi-screenpad/issues/3#issuecomment-1490413864) based on this work, as his implementation is not yet complete.

The FN key lock however was documented by @hieplpvip in his [AsusSMC](https://github.com/hieplpvip/AsusSMC) repo. Additionally, based on your implementation for the keyboard `SKBV` method, I believe this to be your original source. I'm also upstreaming changes to that repo [here](https://github.com/Qonfused/AsusSMC/pull/2) if you want a better look at how DSTS + DEVS methods are used by the screenpad driver (windows).

I have given you attribution in my own repo [here](https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/blob/0c0443683921b29f1cc92b5c627690fe5d317b88/docs/README.md?plain=1#L403) and @shiecldk's repo (fork/PR) [here](https://github.com/Qonfused/ASUS-ZenBook-Pro-Duo-15-UX581-Hackintosh/blob/9e5ee6a983ac629660832b464dbe6091394df27f/README.md?plain=1#L107) for not just the FN+Lock and screenpad changes; your work encompassed the ATKD functionality of the repo. I've since moved away from using ACPI patches to control ATKD methods and the screenpad in [#40](https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/issues/40). The reason why your ACPI patches aren't more commonplace is that they're incorporated in projects like AsusSMC that work between kernelspace + userspace.

**Comment by Qonfused** [comment]
I've outlined the rationale for this in my [#6](https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/issues/6) issue that I linked after you first mentioned/introduced your screenpad fix in [#4](https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/issues/4). I discuss the reasoning for moving away from direct EC register writes here, and for why using DSTS + DEVS methods are preferrable across different devices + BIOS versions.

I have made no error in misrepresenting attribution or the source of own my work, and neither has @shiecldk.

If you're new to the open-source world, attribution is for giving credit based on people's work + time invested; rarely is there novelty in the kind of work done. There is no adversarial relationship here.
