### ISSUE TITLE
BIOS Version Compatibility

### ISSUE THREAD

**Issue by danperks** [shiecldk/ASUS-ZenBook-Pro-Duo-15-OLED-UX582-Hackintosh#3]
I have a UX581 and my BIOS version is at 305, is there anything I need to change in that EFI folder to account for this?
First time trying to setup a hackintosh and dual booting with Windows (hopefully), thanks :)

**Comment by shiecldk** [comment]
Hi @danperks, it should be fine with different BIOS versions as long as you're not modifying the BIOS settings with ifrextract. However, since you're actually booting a different model, I would suggest you clone this project (remember to refer to this GitHub project, of course) and modify your own EFI files (and, of course, the ACPI files). I assume the main things you need to change actually be in the config.plist file. I would mainly look into patching your own displays (main display and ScreenPad), VoodooI2CHID.kext plist, and maybe the keyboard keys (for brightness control, etc).
